### ISSUE TITLE
Navigation: Add easy-to-access 'home' link

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/documentation#32]
Going back to the doc startpage is not obvious to do.

I'd think of a 'doc home' button that brings the reader back to "doc/"

**Comment by joewiz** [comment]
Yes, navigation within this app is limited to the "site-wide" menus - awkward. I'd suggest breadcrumbs: `Documentation Home > Indexing`...

**Comment by miljanuscumlic** [comment]
I would like to support breadcrumbs request, because without them navigating through the docs is not user friendly. Although this might be completely irrelevant and of minor interest to the exist team, but I as a new user of exist find it very important. When I stumbled upon exist website, I explored the documentation pages for a bit to see what's going on. And nonexistent docs-wide navigation was the thing that made me much harder to make a broader picture of the database, its possibilities and the documentation itself.
